### ISSUE TITLE
Analytic Jacobian: passed the test on my computer but my robot won't move

### ISSUE THREAD

**Issue by catachiii** [cmm-21/a2#13]
Dear TA,

I encountered a strange issue. My implementation of analytic jacobian passed the test-a2 on my computer, while it failed the GitHub test. Besides that, I tried to use the analytic Jacobian in test 2.2, the robot will not moving as if I didn't write any code in the IK_solver.h. 

---

I tried to test if my compute_dpdq() function was successfully called in the IK_solver, and it showed yes, then I am more confused why the robot would not move.

---

![image](https://user-images.githubusercontent.com/33168198/111961713-aaaabe00-8af1-11eb-94b8-d5052b025712.png)
![image](https://user-images.githubusercontent.com/33168198/111962367-83082580-8af2-11eb-8209-f3c941a2c05e.png)

**Comment by eastskykang** [comment]
1. github action is currently failing. Please see #3. You can just run the test by yourself 
2. We need more information. Obviously, if the test passes and your IK solver work properly with Jacobian matrix computed by FD, this should work without any problem.

**Comment by catachiii** [comment]
I tried to test it as followed:

This is a small part of IK_solver.h. I tried to calculate analytic jacobian first and overwrite it with estimate jacobian. And this code is working perfectly. 
```
gcrr.compute_dpdq(endEffectorTargets[j].p, endEffectorTargets[j].rb, dpdq); //analytic jacobian
std::cout<<"analytic done!"<<std::endl; 
gcrr.estimate_linear_jacobian(endEffectorTargets[j].p, endEffectorTargets[j].rb, dpdq); //estimate jacobian
std::cout<<"estimate done!"<<std::endl;
```

But if I changed the order, which is
```
gcrr.estimate_linear_jacobian(endEffectorTargets[j].p, endEffectorTargets[j].rb, dpdq); //estimate jacobian
std::cout<<"estimate done!"<<std::endl;
gcrr.compute_dpdq(endEffectorTargets[j].p, endEffectorTargets[j].rb, dpdq); //analytic jacobian
std::cout<<"analytic done!"<<std::endl; 
```
This will result in the same problem I had before. 
And it showed that the calculation is successfully carried out.
![image](https://user-images.githubusercontent.com/33168198/111968819-dd58b480-8af9-11eb-9c36-cb4c7a225ea4.png)

**Comment by eastskykang** [comment]
can you use different matrix variables? 

what happens if 

```cpp
Matrix dpdq2;
gcrr.compute_dpdq(endEffectorTargets[j].p, endEffectorTargets[j].rb, dpdq2);
```

and use ```dpdq2``` for IK?

**Comment by catachiii** [comment]
Still have the same issue. 
I just wonder maybe because my analytical Jacobian calculation is too slow?

**Comment by eastskykang** [comment]
If your analytical Jacobian implementation is correct, it should be much faster than numerical one. However, I don't believe your problem is relevant to the computation speed. 

Please try to print out the value of Jacobians and see if there's any suspicious value. Also, do a double check if your IK solver works properly with numerical Jacobian implementation.

+ and please do use debug mode + breakpoints to identify your problems. You may get a clear view of how the code is executed and which line of your code causes a problem.

**Comment by catachiii** [comment]
I tried another way of implementation, passed the test as well. And my dog finally started to move, but unfortunately, it is not behaving well. I think the test is not enough to validate the correctness of Jacobian.

**Comment by eastskykang** [comment]
As we mentioned, you can consider the provided test as a baseline. Passing all test doesn't mean you get a full point from the exercise neither your implementation is correct.

If you want to extend your test to more general cases, copy paste the provided test code and please write more test cases in your own test code file.

Please consider that the debugging process is also part of this assignment. We hope you learn not only theories behind but also how to implement your logic in C++ code.

**Comment by catachiii** [comment]
Sure! Thanks, Dongho!

**Comment by eastskykang** [comment]
@Catially nonetheless, I appreciate for your report. I think this could be helpful to your colleague students.

**Comment by eastskykang** [comment]
@Catially can you tell me if you fixed your problem? Was it somehow related to #33?

**Comment by catachiii** [comment]
> @Catially can you tell me if you fixed your problem? Was it somehow related to #33?

Yes I have fixed it. The reason of this issue is my wrong implementation of analytical Jacobian. 😂
