### ISSUE TITLE
Task 1

### ISSUE THREAD

**Issue by vullnetu** [cmm-21/a2#14]
Hello

I'm not sure if this is a general bug or I have not finished exercise 1 correctly but the end effectors points in my simulation are below the ground. This was already the case when I launched the code without any changes. Can someone let me know what is the problem ?
<img width="492" alt="Screenshot 2021-03-22 at 14 37 18" src="https://user-images.githubusercontent.com/80257949/111999053-e313c180-8b1c-11eb-999e-b460f10da6b6.png">

**Comment by catachiii** [comment]
check issue #6

**Comment by vullnetu** [comment]
Oh yes I didn't see that. Sorry about that
