### ISSUE TITLE
Calculation of Analytic Jacobian

### ISSUE THREAD

**Issue by PanagiotisAnagnostaras** [cmm-21/a2#16]
Hey everyone,
 I try to do the analytic jacobian but I have some questions:
![body](https://user-images.githubusercontent.com/79992083/112119120-5c62f100-8bbd-11eb-83c9-12dc8ba48558.png)

Don't we need to know the lengths of the links and which q corresponds to each joint, or obtaining this info from the provided code is part of the assignment with reverse engineering?

**Comment by eastskykang** [comment]
Please do not hard code length of links. Your implementation should be general to be used for "any" kind of kinematic tree.

You can access position of joint w.r.t. parent rigid body's coordinate frame by ```joint->pJPos```and position of joint w.r.t. child rigid body's coordinate frame by ```joint->cJPos```

Hope this helps!

**Comment by eastskykang** [comment]
More detailed instruction was given in the last tutorial session. It will be uploaded to the course website shortly. 

Hope this helps!
