### ISSUE TITLE
Unable to clone cmm-21/a2's contents.

### ISSUE THREAD

**Issue by zdchan** [cmm-21/a2#17]
Dear TAs,

After I accept the invitation for task a2, I got this information.

We're sorry, something went wrong.
We were unable to clone cmm-21/a2's contents into cmm-21/a2-zdchan. Please delete this repository and try again.

But I can't find this task in my repositories so I can't delete it. How should I solve this problem?

Thank you for your answer.

**Comment by zdchan** [comment]
I leaved the assignment in setting and now the https://github.com/cmm-21/a2-zdchan becomes 404...

**Comment by eastskykang** [comment]
please try it again now.

**Comment by zdchan** [comment]
> please try it again now.

It's solved. Thank you so much.
