### ISSUE TITLE
Exercise 3 the problem when the forward speed too high

### ISSUE THREAD

**Issue by hkkkpang** [cmm-21/a2#19]
The robot walks in a weird way when the forward speed up to 3 ( as you can see in the screenshot). However, it can still walk in the correct trajectory. The increase of turning speed doesn't affect anything. When the forward speed is lower than 3, it is stable. Is this situation normal for us? Or is it a problem and I should solve it.
![f2e12f0689616285ce358be8dc116dd](https://user-images.githubusercontent.com/80012295/112354147-af779980-8ccc-11eb-9383-e1362c6abc5d.png)

**Comment by eastskykang** [comment]
If the speed command is too high, trajectory is not reachable anymore. (imagine a foot target position is 100 m away from the robot) Thus, it is normal that controller fails. 

Test your controller with the speed in the range of -1.5 ~ 1.5 m/s.
