### ISSUE TITLE
Build: Array overflow in application.h

### ISSUE THREAD

**Issue by Paravain** [cmm-21/a2#20]
I ran into an "Compiler Error C2117" while building application.h: 

on line 99: _screenshotPath[100]_ needs to be _screenshotPath[121]_, 

or it would not build.

**Comment by eastskykang** [comment]
There were some similar error cases reported when the project directory path is too long. 

Please move your project directory to the Desktop (or ```home``` (Linux/macOS) or ```C:\``` (Windows) directory) and try it again.
