### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by fabianje** [cmm-21/a2#21]
Line 40 of test.cpp probably should be `for (uint c = 0; c < dpdq_analytic.cols(); c++) {` (cols instead of rows).

**Comment by eastskykang** [comment]
Ohhh you are right. I will fix it. 

I will announce this in the tomorrow's tutorial session.

**Comment by zdchan** [comment]
So should we change line 39 instead of 40, like the email said? I think changing line 40 will be better.

**Comment by eastskykang** [comment]
@zdchan oh yes it should be line 40. Somehow it was line 39 in my tutorial slide.

**Comment by eastskykang** [comment]
Announced in last tutorial session. Please don't be confused. It is line 40 not 39.
