### ISSUE TITLE
About the ways to implement Question 5

### ISSUE THREAD

**Issue by Hustwireless** [cmm-21/a2#24]
Hi, I'm wondering how to implement the Quesiton 5. 

Do we hard-code the y-offset of the terrain shape into the eepos, or is it suggested to pass the handle of app.ground.ground.meshes into the controller to get the point coordinates of uneven ground and then add it to the y-offset of the eepos?

Thanks!

**Comment by zdchan** [comment]
I think either one will be OK. But for the former one, you may need to pay some effort to read the .ojb file and get the height information.
