### ISSUE TITLE
Question about the auto-check by github

### ISSUE THREAD

**Issue by zdchan** [cmm-21/a2#25]
Dear TAs,

After pushing the changes to github, I can't see the results of the auto grading (no ✔ and no ✖, while others have ✖) and the actions are empty. Is this normal just because I got the invitation for the second time, when you have closed the auto grading?
 
Besides, I have an extra branch apart from main, which I have removed. Do you know where it comes from(I am sorry that I'm not so familiar with github)? 

Thank you so much.

**Comment by catachiii** [comment]
See #3
