### ISSUE TITLE
Robot Model start in ground

### ISSUE THREAD

**Issue by Maenzgi** [cmm-21/a2#26]
Dear TAs and fellow students

I am having a weird issue, and I am not sure if it is my fault or if it is a bug in the program structure: I think I've implemented Task 1 correctly, and the green spheres appear where they should (if I compare them to the images in the readme file). However, for some reason the robot is in the ground. I haven't changed anything in the code except in the two functions that we have to work on in task 1.
<img width="335" alt="Robodog" src="https://user-images.githubusercontent.com/63779517/112506347-f1b4df80-8d8d-11eb-94cc-1f8b53be6aae.PNG">

**Comment by iqiac** [comment]
see #6

**Comment by Maenzgi** [comment]
> 
> 
> see #6

I think it is not the same issue, because my spheres are at the correct position, and only the robot is in the ground. In #6, everything is shifted

**Comment by iqiac** [comment]
Ah sorry. In that case, it looks like something went wrong with maybe the last translation step where you add the x_root (kinematics slide 39). I don't have further ideas at the moment.

**Comment by eastskykang** [comment]
As @iqiac suggested, please see #6 and set the starting height to be 0.5. 

Unless you implement Ex.2, you will see the feet are still under ground. 

(It was 0.5 when I made a screenshot but later I changed it to 0.42)

**Comment by eastskykang** [comment]
BTW somehow (in the image you uploaded) I see the green spheres are not located in correct position. Please do a double check your forward kinematics implementation.
