### ISSUE TITLE
Debugging matrices

### ISSUE THREAD

**Issue by lthiet** [cmm-21/a2#27]
Hi,

Does anyone know how to use the debugger in VS code to see the insides of Eigen Matrices?

This is what I have when debugging : 
![image](https://user-images.githubusercontent.com/26815719/112511378-a5b86980-8d92-11eb-93ca-aec3b931f7b2.png)

the m_data only displays the first value so it is not very useful.

If anyone knows how to display the full matrix in VS code that would be very nice! Thanks

**Comment by eastskykang** [comment]
Unfortunately, debugger does not work very well for eigen matrix. The most easiest solution is printing the matrix with ```std::cout << matrix << std::endl```.

(If someone has a better solution, please let me know!)
