### ISSUE TITLE
fps too low

### ISSUE THREAD

**Issue by boduan1** [cmm-21/a2#32]
I use linux, and I am already in released mode, but it fps is 7.
![Screenshot from 2021-03-28 22-54-22](https://user-images.githubusercontent.com/58148182/112767793-ff31ca00-9018-11eb-8f9e-e8a2f4ea5021.png)
![Screenshot from 2021-03-28 22-54-54](https://user-images.githubusercontent.com/58148182/112767805-0658d800-9019-11eb-90e1-1b9d0e1286bc.png)

**Comment by eastskykang** [comment]
I need more information. Does it drop from 30 fps as you play the app? Or is it already slow when you launch the app? 

(Please be more specific. We cannot reproduce or figure out your problem only with the piece of information you provided here and remember you need some courtesy of your colleagues and TAs to get some advices or tips for your issue)

**Comment by boduan1** [comment]
It doesn't drop, and I tried both command line (adding -DCMAKE_BUILD_TYPE=Release in cmake)
and directly use VScode release mode, both gives 7 fps...
Maybe it is just because my computer is slow?

**Comment by eastskykang** [comment]
I quickly tested your code, and could run your code in real-time on my laptop (macOS 2.4 GHz 8-Core Intel Core i9.) Could you post the system info of your PC? You can go to settings > details.

e.g. 
![image](https://user-images.githubusercontent.com/3031724/112772747-8872ec00-906d-11eb-9288-f79ebe105af9.png)

**Comment by boduan1** [comment]
Thanks! I tried to move to another windows computer, and it works on windows, but the linux system is still slow...
![image](https://user-images.githubusercontent.com/58148182/112803780-f3bfbc80-9073-11eb-83fb-ccf7d3229d7b.png)

**Comment by eastskykang** [comment]
strange. I think your CPU is powerful enough to run the IK solver in real time. 

Can you delete your build directory completely and configure (type configure in your VS code command palette) and build your project from the scratch? If it's still slow, might be related to graphics.

**Comment by Hustwireless** [comment]
Could it be that you are using fractional scale on a high resolution screen?

**Comment by boduan1** [comment]
Oh! that might be the problem! the screen resolution is high...

**Comment by yuliangzhong** [comment]
I have the same problem... even worse! My FPS is only 2-3. I want to know if my code works when you testing... 

> I quickly tested your code, and could run your code in real-time on my laptop (macOS 2.4 GHz 8-Core Intel Core i9.) Could you post the system info of your PC? You can go to settings > details.
> 
> e.g.
> ![image](https://user-images.githubusercontent.com/3031724/112772747-8872ec00-906d-11eb-9288-f79ebe105af9.png)

**Comment by eastskykang** [comment]
If your FPS is too low as soon as you launch the app:

1. double check if your CMake mode is Release 
    - if you use a command line tool (Linux terminal), ```$ cmake -DCMAKE_BUILD_TYPE=Release ../``` when you configure the project with cmake. 
2. try to lower your screen resolution
