### ISSUE TITLE
Test.cpp doesn't work

### ISSUE THREAD

**Issue by Maenzgi** [cmm-21/a2#36]
Dear All

I tried to implement Ex.4, and realized that the test.cpp file doesn't work. I did change the file according to Issue #21. Here is what happens:
![grafik](https://user-images.githubusercontent.com/63779517/113155112-fd465180-9238-11eb-976f-d70be93ea319.png)

My question: Does anybody else have this issue, and if so, how do you fix it?
Also, I did print out my jacobians and compared them by eye. Do I still get the full credit for Ex.4 if my jacobian is correct, even if my test.cpp doesn't work?

Best,
Manuel

**Comment by eastskykang** [comment]
Sorry this is my bad. You should change line 40, not 39 (the announcement was misleading)

So, not this

<img width="548" alt="image" src="https://user-images.githubusercontent.com/3031724/113166091-69e33f80-927d-11eb-8dd6-3ff85ca6c064.png">

but this.

```cpp
 // compare analytic jacobian with estimated one
for (uint r = 0; r < dpdq_analytic.rows(); r++) {
    for (uint c = 0; c < dpdq_analytic.cols(); c++) {
        res += SAME(dpdq_analytic(r, c), dpdq_estimated(r, c), 1e-4);
    }
}
```

related issue: #21
