### ISSUE TITLE
locomotion.exe closed as long as I hit the play button

### ISSUE THREAD

**Issue by breadli428** [cmm-21/a2#4]
Hi,

I am trying to verify my code for task 2.2, however the locomotion.exe will be immediately closed as long as I hit the play button. It seems to be a sign that my coding is somehow wrong, but I am not sure the reason behind.

Is there a way to test task 2.1 and 2.2 separately?

Plus, the ground and the feet of the robot do not align, and this it not an individual case.

Thanks!

**Comment by eastskykang** [comment]
@breadli428 

please see #6 issue for feet-under-the-ground. 

If the app crashes, please change your cmake mode into Debug (you can do this as follows)

![Screenshot from 2021-03-19 13-53-54](https://user-images.githubusercontent.com/3031724/111783576-a2b50900-88ba-11eb-872d-50bc63e97fe0.png)

and click the "launch debugger" (the button with "a bug" shaped icon). This will give you more rich information. (it will stop at the point where the code crashes)

I suggest you to print your Jacobian matrix by ```std::cout``` and see if there's something wrong or not.

**Comment by breadli428** [comment]
Hi Dongho,

Thanks I guess I found the problem. But I have a follow up question.

In function solve in IK_Solver.h, how is nSteps = 10 defined? Where is the time information in endEffectorTargets stored?

Thanks!
