### ISSUE TITLE
Failed to load material file

### ISSUE THREAD

**Issue by catachiii** [cmm-21/a2#5]
Dear TAs, 

I tried to run locomotion app, but it shows this:

Material file [ /home/jin/git/a2-Catially/data/meshes/grid1.mtl ] not found.
Failed to load material file(s). Use default material.

Material file [ /home/jin/git/a2-Catially/data/meshes/grid2.mtl ] not found.
Failed to load material file(s). Use default material.

Both `d` and `Tr` parameters defined for "Default". Use the value of `d` for dissolve (line 8 in .mtl.)

no diffuse texture found for shape `Default`
Segmentation fault (core dumped)

I am not sure about how should I solve this. Can you help me?

**Comment by eastskykang** [comment]
Can you play the app? If that's the case, it's good to ignore the message.

**Comment by catachiii** [comment]
Sorry, no. The app crashed right after all the error messages.

**Comment by catachiii** [comment]
I guess it is not the material file load error because I tried to reconstruct everything but had the same problem. I will check my code again.  

---SOLVED---
The parent index of some joints is in {3,4,5} and I thought it is {0,1,2}, so the while loop won't stop, which results in the problem.
