### ISSUE TITLE
Feet underground

### ISSUE THREAD

**Issue by catachiii** [cmm-21/a2#6]
Dear TAs,

I think I managed to implement the FK in ex1, but the feet of my dog are somehow underground. I guess there is a deviation in the z-direction of the base coordinates of the robot body, should we try to fix it, or is it part of the exercise? I'm not alone with this issue. 

![image](https://user-images.githubusercontent.com/33168198/111757450-a1c0af00-889b-11eb-8e87-df9807a231c4.png)
![image](https://user-images.githubusercontent.com/33168198/111757494-ab4a1700-889b-11eb-8863-242a28e815cf.png)

**Comment by LJRoffler** [comment]
+1

**Comment by eastskykang** [comment]
Hi, all. If you want to change starting base height, 

go to ```src/app/robots.h``` 

```cpp
/* global variable */
std::vector<RobotModel> robotModels = {
    // simple robot models
    RobotModel("Dogbot",                                    //
               CRL_DATA_FOLDER "/robots/cora/cora_v4.rbs",  //
               "",                                          //
               "tibia_0",                                   //
               "tibia_1",                                   //
               "tibia_2",                                   //
               "tibia_3",                                   //
               0.42,                                        //  change this value to ~0.5
               0.42,                                        //
               0.10),

};
```

BTW once you implement IK solver successfully, you will see the feet move up and down from the ground. (it won't go under the ground anymore)
