### ISSUE TITLE
Where to find terrain file

### ISSUE THREAD

**Issue by breadli428** [cmm-21/a2#9]
Hi,

I was trying to do Ex 5, however I had problem locating the terrain file. I tried to search but a lot of similar result came out and I did not manage to find the code where it loads the terrain.

Could you please give more information on this?

Thanks!

**Comment by eastskykang** [comment]
You can create your own terrain by adding some large spheres in the scene as I mentioned earlier. 

If you want to use heightmap, try one in the data folder. But, loading terrain.obj file in the scene (as well as getting the height of the ground for the target) would require some extra work.

**Comment by breadli428** [comment]
-"You can create your own terrain by adding some large spheres in the scene as I mentioned earlier."

Yes, but where, actually? In terrain.obj?

**Comment by eastskykang** [comment]
@breadli428 I'm closing this issue. Please reopen once you encounter another problem.
